name: Build in Ubuntu-24.04 (Runner)

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out repository
        uses: actions/checkout@v5
      -
        name: Install R
        run: |
          apt-get update && apt-get install -y wget
          wget https://raw.githubusercontent.com/sigmaresearch100/r-ubuntu-24.04/main/tools/build.sh
          bash build.sh
      -
        name: remotes and rprojroot
        run: sudo Rscript ${PWD}/tools/000.R
      -
        name: system dependencies
        run: sudo bash ${PWD}/tools/dep.sh
      -
        name: R dependencies
        run: sudo Rscript ${PWD}/tools/dep.R
      -
        name: build package
        run: sudo bash ${PWD}/tools/build.sh
