name: Build in Ubuntu-24.04 (Docker)

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04

    steps:
      -
        name: Check out repository
        uses: actions/checkout@v5
      -
        name: Install R
        run: |
          apt-get update && apt-get install -y wget
          wget https://raw.githubusercontent.com/sigmaresearch100/r-ubuntu-24.04/main/tools/build.sh
          bash build.sh
      -
        name: Install remotes and rprojroot
        run: Rscript ${PWD}/tools/000.R
      -
        name: Install system dependencies
        run: bash ${PWD}/tools/dep.sh
      -
        name: Install R dependencies
        run: Rscript ${PWD}/tools/dep.R
      -
        name: Build package
        run: bash ${PWD}/tools/build.sh
